// <auto-generated />
namespace MVC_Blog_Bountry_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class yeniEkle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yeniEkle));
        
        string IMigrationMetadata.Id
        {
            get { return "201912111242028_yeniEkle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
